/* Generated By:JavaCC: Do not edit this line. BooleanFormulaParserConstants.java */
package com.booleworks.logicng.io.parsers.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BooleanFormulaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int LITERAL = 6;
  /** RegularExpression Id. */
  int TRUE = 7;
  /** RegularExpression Id. */
  int FALSE = 8;
  /** RegularExpression Id. */
  int LBR = 9;
  /** RegularExpression Id. */
  int RBR = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int OR = 13;
  /** RegularExpression Id. */
  int IMPL = 14;
  /** RegularExpression Id. */
  int EQUIV = 15;
  /** RegularExpression Id. */
  int MUL = 16;
  /** RegularExpression Id. */
  int ADD = 17;
  /** RegularExpression Id. */
  int EQ = 18;
  /** RegularExpression Id. */
  int LE = 19;
  /** RegularExpression Id. */
  int LT = 20;
  /** RegularExpression Id. */
  int GE = 21;
  /** RegularExpression Id. */
  int GT = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUMBER>",
    "<LITERAL>",
    "\"$true\"",
    "\"$false\"",
    "\"(\"",
    "\")\"",
    "\"~\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"<=>\"",
    "\"*\"",
    "<ADD>",
    "\"=\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
  };

}
